### ISSUE TITLE
evaluación

### ISSUE THREAD

**Issue by crguezl** [ULL-MII-SYTWS-2223/intro2sd-claudio_nestor-yanes-mesa-alu0101229942#11]
Buen trabajo @claudio4   👍 

Quizá hablar en el informe  de algunos puntos:

* Se ha creado una Jekyll Collection
*  Se ha hecho uso de liquid (mostrar ejemplo en el informe)
* Se ha hecho uso de un .csv o .json en `_data` (mostrar ejemplo en el informe)
*  Has reconfigurado los defaults del _config.yml

**Comment by crguezl** [comment]
Y claro, el informe del capítulo que había que leer se podría mejorar

También sería conveniente suprimir el resto de posts y páginas no usadas

**Comment by crguezl** [comment]
Otra cosa que veremos hoy es lo de hacer un 404 dinámico usando web services

**Comment by claudio4** [comment]
@crguezl He añadido nuevos commits con lo que me faltaba

**Comment by crguezl** [comment]
Perfecto! 🚀
